build: build-readme
	@echo "Build succeeded! I'm waiting for your contribution on GitHub!"
	@echo "https://github.com/ariarijp/list-of-companies-using-redash"

build-json:
	@jq -c '. | sort_by(.company_name) | .[]' --sort-keys --slurp jp/companies.json > jp/companies.json.tmp
	@mv jp/companies.json.tmp jp/companies.json

build-readme: build-json
	@echo "# list-of-companies-using-redash(Japan)" > jp/README.md
	@echo "" >> jp/README.md
	@echo "NOTE: This file is autogenerated. Do not edit it manually." >> jp/README.md
	@echo "" >> jp/README.md
	@echo "## List of companies" >> jp/README.md
	@echo "" >> jp/README.md
	@echo "| Name | URL |" >> jp/README.md
	@echo "| --- | --- |" >> jp/README.md
	@jq -c '. | sort_by(.company_name) | .[] | "| \(.company_name) | \(.company_url) |"' -r --sort-keys --slurp jp/companies.json >> jp/README.md

.PHONY: build build-json build-readme
